# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 603)
        MainWindow.setMinimumSize(QtCore.QSize(789, 603))
        MainWindow.setMaximumSize(QtCore.QSize(789, 603))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 211, 581))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 150, 161, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 210, 161, 41))
        self.pushButton_6.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 440, 141, 41))
        self.pushButton_8.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 370, 141, 41))
        self.pushButton_9.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 0, 571, 591))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(0, 11, 561, 581))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setStyleSheet("box-shadow: 0 8px 6px -6px black;\n"
                                   "")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.zoneLabel = QtWidgets.QLabel(self.frame_2)
        self.zoneLabel.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.zoneLabel.setObjectName("zoneLabel")
        self.zoneComBox = QtWidgets.QComboBox(self.frame_2)
        self.zoneComBox.setGeometry(QtCore.QRect(110, 20, 71, 22))
        self.zoneComBox.setAcceptDrops(True)
        self.zoneComBox.setStyleSheet("\n"
                                      ".QComboBox{\n"
                                      "    border: 2px solid #4CAF50;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      "\n"
                                      "QComboBox::down-arrow {\n"
                                      "    position: relative;\n"
                                      "     height: 15px;\n"
                                      "     width: 15px;\n"
                                      "    border: 12px;\n"
                                      " \n"
                                      "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                      "}\n"
                                      "QComboBox::drop-down {\n"
                                      "    border: 0px; \n"
                                      "}\n"
                                      "")
        self.zoneComBox.setObjectName("zoneComBox")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 20))
        self.label_2.setObjectName("label_2")
        self.branchAddress = QtWidgets.QLineEdit(self.frame_2)
        self.branchAddress.setGeometry(QtCore.QRect(140, 100, 381, 21))
        self.branchAddress.setStyleSheet("border-bottom:1px solid #eee;\n"
                                         "border:0;\n"
                                         "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                         "border-radius:5px;\n"
                                         "height:10px;\n"
                                         "")
        self.branchAddress.setText("")
        self.branchAddress.setReadOnly(False)
        self.branchAddress.setObjectName("branchAddress")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(240, 22, 71, 16))
        self.label_3.setObjectName("label_3")
        self.bankComBox = QtWidgets.QComboBox(self.frame_2)
        self.bankComBox.setGeometry(QtCore.QRect(320, 20, 201, 22))
        self.bankComBox.setAcceptDrops(True)
        self.bankComBox.setStyleSheet("\n"
                                      ".QComboBox{\n"
                                      "    border: 2px solid #4CAF50;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      "QComboBox::down-arrow {\n"
                                      "    position: relative;\n"
                                      "     height: 15px;\n"
                                      "     width: 15px;\n"
                                      "    border: 12px;\n"
                                      " \n"
                                      "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                      "}\n"
                                      "QComboBox::drop-down {\n"
                                      "    border: 0px; \n"
                                      "}\n"
                                      "\n"
                                      "")
        self.bankComBox.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox.setObjectName("bankComBox")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 60, 91, 20))
        self.lineEdit_2.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(389, 60, 131, 22))
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setStyleSheet("\n"
                                    "QDateEdit{\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "}\n"
                                    "QDateEdit::up-button {subcontrol-origin:border;\n"
                                    "    subcontrol-position:right;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_3.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;       \n"
                                    "}\n"
                                    "QDateEdit::down-button{subcontrol-origin:border;\n"
                                    "    subcontrol-position:left;\n"
                                    "image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_1.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;\n"
                                    "}\n"
                                    "QDateEdit::up-button:pressed{subcontrol-origin:border;\n"
                                    "    subcontrol-position:right;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_2.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;       \n"
                                    "}\n"
                                    "  \n"
                                    "QDateEdit::down-button:pressed{\n"
                                    "    subcontrol-position:left;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_2.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;\n"
                                    "}")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2021, 3, 13), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setDate(QtCore.QDate(2021, 3, 13))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(280, 60, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(140, 140, 161, 21))
        self.label_6.setObjectName("label_6")
        self.visitTypeComBox = QtWidgets.QComboBox(self.frame_2)
        self.visitTypeComBox.setGeometry(QtCore.QRect(310, 140, 71, 22))
        self.visitTypeComBox.setStyleSheet("\n"
                                           ".QComboBox{\n"
                                           "    border: 2px solid #4CAF50;\n"
                                           " }\n"
                                           "\n"
                                           "\n"
                                           "\n"
                                           "QComboBox::down-arrow {\n"
                                           "    position: relative;\n"
                                           "     height: 10px;\n"
                                           "     width: 10px;\n"
                                           "    border: 10px;\n"
                                           " \n"
                                           "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                           "}\n"
                                           "QComboBox::drop-down {\n"
                                           "    border: 0px; \n"
                                           "}\n"
                                           "")
        self.visitTypeComBox.setObjectName("visitTypeComBox")
        self.visitTypeComBox.addItem("")
        self.visitTypeComBox.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 140, 41, 21))
        self.lineEdit_3.setStyleSheet(".QLineEdit{\n"
                                      "border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;\n"
                                      "}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(442, 140, 81, 21))
        self.lineEdit_4.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.label_7.setStyleSheet("border: 2px solid #4CAF50; \n"
                                   "")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 210, 231, 20))
        self.lineEdit_5.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 250, 151, 20))
        self.lineEdit_6.setStyleSheet("\n"
                                      "border:0;\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(80, 250, 47, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(390, 210, 61, 16))
        self.label_10.setObjectName("label_10")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(450, 211, 71, 21))
        self.spinBox.setStyleSheet("QSpinBox{\n"
                                   "qproperty-alignment: AlignCenter;}\n"
                                   "QSpinBox::up-arrow {\n"
                                   "image:url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px.png\");\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "QSpinBox::up-button { \n"
                                   "subcontrol-origin:border;\n"
                                   "  subcontrol-position:right;   \n"
                                   "  width: 22px;\n"
                                   "  height: 20px;\n"
                                   "border:0;\n"
                                   " }\n"
                                   "\n"
                                   "\n"
                                   " \n"
                                   "QSpinBox::down-arrow { \n"
                                   "image:url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px.png\");}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   " \n"
                                   " QSpinBox::down-button { \n"
                                   "border:0px;\n"
                                   "subcontrol-origin:border;\n"
                                   "  subcontrol-position:left;\n"
                                   "  width: 22px;\n"
                                   "  height: 20px; \n"
                                   "\n"
                                   "}\n"
                                   "QSpinBox::up-button:pressed{subcontrol-origin:border;\n"
                                   "    subcontrol-position:right;\n"
                                   "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_2.png\");\n"
                                   "    width: 22px;\n"
                                   "    height: 20px;       \n"
                                   "}\n"
                                   "  \n"
                                   "QSpinBox::down-button:pressed\n"
                                   "{\n"
                                   "    subcontrol-position:left;\n"
                                   "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_2.png\");\n"
                                   "    width: 22px;\n"
                                   "    height: 20px;\n"
                                   "}\n"
                                   "")
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(424, 250, 101, 23))
        self.pushButton.setStyleSheet(".QPushButton {\n"
                                      "  background-color: white;\n"
                                      "  color: black;\n"
                                      "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                      "}\n"
                                      "\n"
                                      ".QPushButton {\n"
                                      "  transition-duration: 0.4s;\n"
                                      "}\n"
                                      "\n"
                                      ".QPushButton:hover {\n"
                                      "  background-color: rgb(85, 170, 127); /* Green */\n"
                                      "  color: white;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 530, 81, 31))
        self.pushButton_2.setStyleSheet(".QPushButton {\n"
                                        "  background-color: white;\n"
                                        "  color: black;\n"
                                        "  border: 2px solid rgb(85, 170, 127);\n"
                                        "  font: 10pt \"MS Shell Dlg 2\";\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton {\n"
                                        "  transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton:hover {\n"
                                        "  background-color: rgb(85, 170, 127); /* Green */\n"
                                        "  color: white;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 530, 71, 31))
        self.pushButton_3.setStyleSheet(".QPushButton {\n"
                                        "  background-color: white;\n"
                                        "  color: black;\n"
                                        "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                        "font: 10pt \"MS Shell Dlg 2\";\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton {\n"
                                        "  transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton:hover {\n"
                                        "  background-color:rgb(85, 170, 127); /* Green */\n"
                                        "  color: white;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(30, 290, 491, 221))
        self.tableWidget.setStyleSheet("\n"
                                       "QHeaderView::section\n"
                                       "\n"
                                       "{\n"
                                       " Font-size:14px; \n"
                                       " Font-family: \"Microsoft YaHei\"; \n"
                                       " Color: #FFFFFF; \n"
                                       " \n"
                                       " Background:rgb(85, 170, 127); \n"
                                       "Border:1px; \n"
                                       " Text-align:left;\n"
                                       " \n"
                                       " \n"
                                       " Min-height: 34px;\n"
                                       " max-height:34px; \n"
                                       "\n"
                                       "\n"
                                       " Margin:0px;\n"
                                       " Padding: 0px;\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(122)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_6 = QtWidgets.QFrame(self.page_4)
        self.frame_6.setGeometry(QtCore.QRect(0, 10, 561, 581))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(2)
        self.frame_6.setMidLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setGeometry(QtCore.QRect(330, 30, 121, 20))
        self.label_11.setObjectName("label_11")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 70, 531, 461))
        self.tableWidget_2.setStyleSheet("\n"
                                         "QHeaderView::section\n"
                                         "\n"
                                         "{\n"
                                         " Font-size:14px; \n"
                                         " Font-family: \"Microsoft YaHei\"; \n"
                                         " Color: #FFFFFF; \n"
                                         " \n"
                                         " Background:rgb(85, 170, 127); \n"
                                         "Border:1px; \n"
                                         " Text-align:left;\n"
                                         " \n"
                                         " \n"
                                         " Min-height: 34px;\n"
                                         " max-height:34px; \n"
                                         "\n"
                                         "\n"
                                         " Margin:0px;\n"
                                         " Padding: 0px;\n"
                                         "\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "")
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(19)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(460, 30, 91, 20))
        self.lineEdit_7.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.bankComBox_3 = QtWidgets.QComboBox(self.frame_6)
        self.bankComBox_3.setGeometry(QtCore.QRect(120, 30, 201, 22))
        self.bankComBox_3.setAcceptDrops(True)
        self.bankComBox_3.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "\n"
                                        "")
        self.bankComBox_3.setInsertPolicy(
            QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox_3.setObjectName("bankComBox_3")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.zoneComBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.zoneComBox_2.setGeometry(QtCore.QRect(30, 30, 71, 22))
        self.zoneComBox_2.setAcceptDrops(True)
        self.zoneComBox_2.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "")
        self.zoneComBox_2.setObjectName("zoneComBox_2")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setGeometry(QtCore.QRect(467, 540, 70, 31))
        self.pushButton_14.setStyleSheet(".QPushButton {\n"
                                         "  background-color: white;\n"
                                         "  color: black;\n"
                                         "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                         "font: 10pt \"MS Shell Dlg 2\";\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton {\n"
                                         "  transition-duration: 0.4s;\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton:hover {\n"
                                         "  background-color:rgb(85, 170, 127); /* Green */\n"
                                         "  color: white;\n"
                                         "}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_8 = QtWidgets.QFrame(self.page_3)
        self.frame_8.setGeometry(QtCore.QRect(0, 10, 561, 581))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.frame_8.setMidLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.label_38 = QtWidgets.QLabel(self.frame_8)
        self.label_38.setGeometry(QtCore.QRect(330, 30, 121, 20))
        self.label_38.setObjectName("label_38")
        self.tableWidget_10 = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_10.setEnabled(True)
        self.tableWidget_10.setGeometry(QtCore.QRect(20, 70, 531, 491))
        self.tableWidget_10.setStyleSheet("\n"
                                          "QHeaderView::section\n"
                                          "\n"
                                          "{\n"
                                          " Font-size:14px; \n"
                                          " Font-family: \"Microsoft YaHei\"; \n"
                                          " Color: #FFFFFF; \n"
                                          " \n"
                                          " Background:rgb(85, 170, 127); \n"
                                          "Border:1px; \n"
                                          " Text-align:left;\n"
                                          " \n"
                                          " \n"
                                          " Min-height: 34px;\n"
                                          " max-height:34px; \n"
                                          "\n"
                                          "\n"
                                          " Margin:0px;\n"
                                          " Padding: 0px;\n"
                                          "\n"
                                          "}\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "\n"
                                          "")
        self.tableWidget_10.setLineWidth(1)
        self.tableWidget_10.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_10.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_10.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_10.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_10.setShowGrid(True)
        self.tableWidget_10.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_10.setRowCount(0)
        self.tableWidget_10.setColumnCount(6)
        self.tableWidget_10.setObjectName("tableWidget_10")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_10.setHorizontalHeaderItem(5, item)
        self.tableWidget_10.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_10.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_10.horizontalHeader().setHighlightSections(False)
        self.tableWidget_10.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_10.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_10.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_10.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_10.verticalHeader().setMinimumSectionSize(19)
        self.tableWidget_10.verticalHeader().setStretchLastSection(False)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_24.setGeometry(QtCore.QRect(460, 30, 91, 20))
        self.lineEdit_24.setStyleSheet("border-bottom:1px solid #eee;\n"
                                       "border:0;\n"
                                       "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                       "border-radius:5px;\n"
                                       "height:10px;")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.bankComBox_10 = QtWidgets.QComboBox(self.frame_8)
        self.bankComBox_10.setGeometry(QtCore.QRect(120, 30, 201, 22))
        self.bankComBox_10.setAcceptDrops(True)
        self.bankComBox_10.setStyleSheet("\n"
                                         ".QComboBox{\n"
                                         "    border: 2px solid #4CAF50;\n"
                                         " }\n"
                                         "\n"
                                         "\n"
                                         "QComboBox::down-arrow {\n"
                                         "    position: relative;\n"
                                         "     height: 15px;\n"
                                         "     width: 15px;\n"
                                         "    border: 12px;\n"
                                         " \n"
                                         "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                         "}\n"
                                         "QComboBox::drop-down {\n"
                                         "    border: 0px; \n"
                                         "}\n"
                                         "\n"
                                         "")
        self.bankComBox_10.setInsertPolicy(
            QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox_10.setObjectName("bankComBox_10")
        self.bankComBox_10.addItem("")
        self.bankComBox_10.addItem("")
        self.bankComBox_10.addItem("")
        self.bankComBox_10.addItem("")
        self.zoneComBox_11 = QtWidgets.QComboBox(self.frame_8)
        self.zoneComBox_11.setGeometry(QtCore.QRect(30, 30, 71, 22))
        self.zoneComBox_11.setAcceptDrops(True)
        self.zoneComBox_11.setStyleSheet("\n"
                                         ".QComboBox{\n"
                                         "    border: 2px solid #4CAF50;\n"
                                         " }\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "QComboBox::down-arrow {\n"
                                         "    position: relative;\n"
                                         "     height: 15px;\n"
                                         "     width: 15px;\n"
                                         "    border: 12px;\n"
                                         " \n"
                                         "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                         "}\n"
                                         "QComboBox::drop-down {\n"
                                         "    border: 0px; \n"
                                         "}\n"
                                         "")
        self.zoneComBox_11.setObjectName("zoneComBox_11")
        self.zoneComBox_11.addItem("")
        self.zoneComBox_11.addItem("")
        self.zoneComBox_11.addItem("")
        self.zoneComBox_11.addItem("")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setGeometry(QtCore.QRect(0, 11, 561, 581))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(2)
        self.frame_7.setMidLineWidth(2)
        self.frame_7.setObjectName("frame_7")
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        self.label_24.setGeometry(QtCore.QRect(330, 30, 121, 20))
        self.label_24.setObjectName("label_24")
        self.tableWidget_9 = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget_9.setEnabled(True)
        self.tableWidget_9.setGeometry(QtCore.QRect(20, 70, 531, 461))
        self.tableWidget_9.setStyleSheet("\n"
                                         "QHeaderView::section\n"
                                         "\n"
                                         "{\n"
                                         " Font-size:14px; \n"
                                         " Font-family: \"Microsoft YaHei\"; \n"
                                         " Color: #FFFFFF; \n"
                                         " \n"
                                         " Background:rgb(85, 170, 127); \n"
                                         "Border:1px; \n"
                                         " Text-align:left;\n"
                                         " \n"
                                         " \n"
                                         " Min-height: 34px;\n"
                                         " max-height:34px; \n"
                                         "\n"
                                         "\n"
                                         " Margin:0px;\n"
                                         " Padding: 0px;\n"
                                         "\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "")
        self.tableWidget_9.setLineWidth(1)
        self.tableWidget_9.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_9.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_9.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_9.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_9.setShowGrid(True)
        self.tableWidget_9.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_9.setRowCount(0)
        self.tableWidget_9.setColumnCount(6)
        self.tableWidget_9.setObjectName("tableWidget_9")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tableWidget_9.setHorizontalHeaderItem(5, item)
        self.tableWidget_9.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_9.horizontalHeader().setDefaultSectionSize(106)
        self.tableWidget_9.horizontalHeader().setHighlightSections(False)
        self.tableWidget_9.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_9.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_9.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_9.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget_9.verticalHeader().setMinimumSectionSize(19)
        self.tableWidget_9.verticalHeader().setStretchLastSection(False)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_23.setGeometry(QtCore.QRect(460, 30, 91, 20))
        self.lineEdit_23.setStyleSheet("border-bottom:1px solid #eee;\n"
                                       "border:0;\n"
                                       "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                       "border-radius:5px;\n"
                                       "height:10px;")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.bankComBox_9 = QtWidgets.QComboBox(self.frame_7)
        self.bankComBox_9.setGeometry(QtCore.QRect(120, 30, 201, 22))
        self.bankComBox_9.setAcceptDrops(True)
        self.bankComBox_9.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "\n"
                                        "")
        self.bankComBox_9.setInsertPolicy(
            QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox_9.setObjectName("bankComBox_9")
        self.bankComBox_9.addItem("")
        self.bankComBox_9.addItem("")
        self.bankComBox_9.addItem("")
        self.bankComBox_9.addItem("")
        self.zoneComBox_10 = QtWidgets.QComboBox(self.frame_7)
        self.zoneComBox_10.setGeometry(QtCore.QRect(30, 30, 71, 22))
        self.zoneComBox_10.setAcceptDrops(True)
        self.zoneComBox_10.setStyleSheet("\n"
                                         ".QComboBox{\n"
                                         "    border: 2px solid #4CAF50;\n"
                                         " }\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "QComboBox::down-arrow {\n"
                                         "    position: relative;\n"
                                         "     height: 15px;\n"
                                         "     width: 15px;\n"
                                         "    border: 12px;\n"
                                         " \n"
                                         "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                         "}\n"
                                         "QComboBox::drop-down {\n"
                                         "    border: 0px; \n"
                                         "}\n"
                                         "")
        self.zoneComBox_10.setObjectName("zoneComBox_10")
        self.zoneComBox_10.addItem("")
        self.zoneComBox_10.addItem("")
        self.zoneComBox_10.addItem("")
        self.zoneComBox_10.addItem("")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_17.setGeometry(QtCore.QRect(471, 541, 71, 31))
        self.pushButton_17.setStyleSheet(".QPushButton {\n"
                                         "  background-color: white;\n"
                                         "  color: black;\n"
                                         "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                         "font: 10pt \"MS Shell Dlg 2\";\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton {\n"
                                         "  transition-duration: 0.4s;\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton:hover {\n"
                                         "  background-color:rgb(85, 170, 127); /* Green */\n"
                                         "  color: white;\n"
                                         "}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_18.setGeometry(QtCore.QRect(381, 540, 71, 31))
        self.pushButton_18.setStyleSheet(".QPushButton {\n"
                                         "  background-color: white;\n"
                                         "  color: black;\n"
                                         "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                         "font: 10pt \"MS Shell Dlg 2\";\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton {\n"
                                         "  transition-duration: 0.4s;\n"
                                         "}\n"
                                         "\n"
                                         ".QPushButton:hover {\n"
                                         "  background-color:rgb(85, 170, 127); /* Green */\n"
                                         "  color: white;\n"
                                         "}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(self.showAddQuotaionTab)
        self.pushButton_6.clicked.connect(self.showAddBillTab)
        self.pushButton_8.clicked.connect(self.showQuotaionTab)
        self.pushButton_9.clicked.connect(self.showBillTab)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showAddQuotaionTab(self):
        self.stackedWidget.setCurrentIndex(0)

    def showAddBillTab(self):
        self.stackedWidget.setCurrentIndex(1)

    def showQuotaionTab(self):
        self.stackedWidget.setCurrentIndex(3)

    def showBillTab(self):
        self.stackedWidget.setCurrentIndex(2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Add A Quotation"))
        self.pushButton_6.setText(_translate("MainWindow", "Add A Bill"))
        self.pushButton_8.setText(_translate("MainWindow", "Quotations"))
        self.pushButton_9.setText(_translate("MainWindow", "Bills"))
        self.zoneLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Zone:</span></p></body></html>"))
        self.zoneComBox.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox.setItemText(3, _translate("MainWindow", "KPK"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Branch:</span></p></body></html>"))
        self.branchAddress.setPlaceholderText(
            _translate("MainWindow", "Enter Bank Branch Address"))
        self.label_3.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Bank:</span></p></body></html>"))
        self.bankComBox.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox.setItemText(2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox.setItemText(3, _translate(
            "MainWindow", "DUBAI ISLAMIC BANK"))
        self.label_4.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainWindow", "1"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_5.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Date of Complaint:</span></p></body></html>"))
        self.label_6.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Visit / Conveynce Charges:</span></p></body></html>"))
        self.visitTypeComBox.setItemText(0, _translate("MainWindow", "Visit"))
        self.visitTypeComBox.setItemText(
            1, _translate("MainWindow", "Conveynce"))
        self.label_7.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Services:</span></p></body></html>"))
        self.label_8.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Service Description:</span></p></body></html>"))
        self.label_9.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Details:</span></p></body></html>"))
        self.label_10.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Quantity:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Add A Service"))
        self.pushButton_2.setText(_translate("MainWindow", "Finalize"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rate"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.label_11.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Complain No"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bank Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bank Address"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Amount"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Invoice No"))
        self.bankComBox_3.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox_3.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox_3.setItemText(
            2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox_3.setItemText(
            3, _translate("MainWindow", "DUBAI ISLAMIC BANK"))
        self.zoneComBox_2.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox_2.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox_2.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox_2.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox_2.setItemText(3, _translate("MainWindow", "KPK"))
        self.pushButton_14.setText(_translate("MainWindow", "Add Bill"))
        self.label_38.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.tableWidget_10.setSortingEnabled(False)
        item = self.tableWidget_10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Complain No"))
        item = self.tableWidget_10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bank Name"))
        item = self.tableWidget_10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bank Address"))
        item = self.tableWidget_10.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Amount"))
        item = self.tableWidget_10.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_10.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Invoice No"))
        self.bankComBox_10.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox_10.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox_10.setItemText(
            2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox_10.setItemText(
            3, _translate("MainWindow", "DUBAI ISLAMIC BANK"))
        self.zoneComBox_11.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox_11.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox_11.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox_11.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox_11.setItemText(3, _translate("MainWindow", "KPK"))
        self.label_24.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.tableWidget_9.setSortingEnabled(False)
        item = self.tableWidget_9.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Complain No"))
        item = self.tableWidget_9.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bank Name"))
        item = self.tableWidget_9.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bank Address"))
        item = self.tableWidget_9.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total Amount"))
        item = self.tableWidget_9.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_9.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Invoice No"))
        self.bankComBox_9.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox_9.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox_9.setItemText(
            2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox_9.setItemText(
            3, _translate("MainWindow", "DUBAI ISLAMIC BANK"))
        self.zoneComBox_10.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox_10.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox_10.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox_10.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox_10.setItemText(3, _translate("MainWindow", "KPK"))
        self.pushButton_17.setText(_translate("MainWindow", "Delete"))
        self.pushButton_18.setText(_translate("MainWindow", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
