# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'B.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 741)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 211, 581))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 150, 161, 41))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 210, 161, 41))
        self.pushButton_6.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 440, 141, 41))
        self.pushButton_8.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_8.setFlat(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 370, 141, 41))
        self.pushButton_9.setStyleSheet(".QPushButton {\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "border-radius: 20px;\n"
                                        "font-size:15px;\n"
                                        "background-color:rgb(85, 170, 127);\n"
                                        "}")
        self.pushButton_9.setFlat(False)
        self.pushButton_9.setObjectName("pushButton_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(220, 10, 571, 611))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 541, 571))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setStyleSheet("box-shadow: 0 8px 6px -6px black;\n"
                                   "")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.zoneLabel = QtWidgets.QLabel(self.frame_2)
        self.zoneLabel.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.zoneLabel.setObjectName("zoneLabel")
        self.zoneComBox = QtWidgets.QComboBox(self.frame_2)
        self.zoneComBox.setGeometry(QtCore.QRect(110, 20, 71, 22))
        self.zoneComBox.setAcceptDrops(True)
        self.zoneComBox.setStyleSheet("\n"
                                      ".QComboBox{\n"
                                      "    border: 2px solid #4CAF50;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      "\n"
                                      "QComboBox::down-arrow {\n"
                                      "    position: relative;\n"
                                      "     height: 15px;\n"
                                      "     width: 15px;\n"
                                      "    border: 12px;\n"
                                      " \n"
                                      "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                      "}\n"
                                      "QComboBox::drop-down {\n"
                                      "    border: 0px; \n"
                                      "}\n"
                                      "")
        self.zoneComBox.setObjectName("zoneComBox")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.zoneComBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 20))
        self.label_2.setObjectName("label_2")
        self.branchAddress = QtWidgets.QLineEdit(self.frame_2)
        self.branchAddress.setGeometry(QtCore.QRect(140, 100, 381, 21))
        self.branchAddress.setStyleSheet("border-bottom:1px solid #eee;\n"
                                         "border:0;\n"
                                         "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                         "border-radius:5px;\n"
                                         "height:10px;\n"
                                         "")
        self.branchAddress.setText("")
        self.branchAddress.setReadOnly(False)
        self.branchAddress.setObjectName("branchAddress")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(240, 22, 71, 16))
        self.label_3.setObjectName("label_3")
        self.bankComBox = QtWidgets.QComboBox(self.frame_2)
        self.bankComBox.setGeometry(QtCore.QRect(320, 20, 201, 22))
        self.bankComBox.setAcceptDrops(True)
        self.bankComBox.setStyleSheet("\n"
                                      ".QComboBox{\n"
                                      "    border: 2px solid #4CAF50;\n"
                                      " }\n"
                                      "\n"
                                      "\n"
                                      "QComboBox::down-arrow {\n"
                                      "    position: relative;\n"
                                      "     height: 15px;\n"
                                      "     width: 15px;\n"
                                      "    border: 12px;\n"
                                      " \n"
                                      "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                      "}\n"
                                      "QComboBox::drop-down {\n"
                                      "    border: 0px; \n"
                                      "}\n"
                                      "\n"
                                      "")
        self.bankComBox.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox.setObjectName("bankComBox")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.bankComBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 60, 91, 20))
        self.lineEdit_2.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(389, 60, 131, 22))
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setStyleSheet("\n"
                                    "QDateEdit{\n"
                                    "qproperty-alignment: AlignCenter;\n"
                                    "}\n"
                                    "QDateEdit::up-button {subcontrol-origin:border;\n"
                                    "    subcontrol-position:right;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_3.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;       \n"
                                    "}\n"
                                    "QDateEdit::down-button{subcontrol-origin:border;\n"
                                    "    subcontrol-position:left;\n"
                                    "image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_1.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;\n"
                                    "}\n"
                                    "QDateEdit::up-button:pressed{subcontrol-origin:border;\n"
                                    "    subcontrol-position:right;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_2.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;       \n"
                                    "}\n"
                                    "  \n"
                                    "QDateEdit::down-button:pressed{\n"
                                    "    subcontrol-position:left;\n"
                                    "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_2.png\");\n"
                                    "    width: 22px;\n"
                                    "    height: 20px;\n"
                                    "}")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setDateTime(QtCore.QDateTime(
            QtCore.QDate(2021, 3, 13), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setDate(QtCore.QDate(2021, 3, 13))
        self.dateEdit.setObjectName("dateEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(280, 60, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(140, 140, 161, 21))
        self.label_6.setObjectName("label_6")
        self.visitTypeComBox = QtWidgets.QComboBox(self.frame_2)
        self.visitTypeComBox.setGeometry(QtCore.QRect(310, 140, 71, 22))
        self.visitTypeComBox.setStyleSheet("\n"
                                           ".QComboBox{\n"
                                           "    border: 2px solid #4CAF50;\n"
                                           " }\n"
                                           "\n"
                                           "\n"
                                           "\n"
                                           "QComboBox::down-arrow {\n"
                                           "    position: relative;\n"
                                           "     height: 10px;\n"
                                           "     width: 10px;\n"
                                           "    border: 10px;\n"
                                           " \n"
                                           "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                           "}\n"
                                           "QComboBox::drop-down {\n"
                                           "    border: 0px; \n"
                                           "}\n"
                                           "")
        self.visitTypeComBox.setObjectName("visitTypeComBox")
        self.visitTypeComBox.addItem("")
        self.visitTypeComBox.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 140, 41, 21))
        self.lineEdit_3.setStyleSheet(".QLineEdit{\n"
                                      "border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;\n"
                                      "}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(442, 140, 81, 21))
        self.lineEdit_4.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.label_7.setStyleSheet("border: 2px solid #4CAF50; \n"
                                   "")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 210, 231, 20))
        self.lineEdit_5.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 250, 151, 20))
        self.lineEdit_6.setStyleSheet("\n"
                                      "border:0;\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(80, 250, 47, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(390, 210, 61, 16))
        self.label_10.setObjectName("label_10")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(450, 211, 71, 21))
        self.spinBox.setStyleSheet("QSpinBox{\n"
                                   "qproperty-alignment: AlignCenter;}\n"
                                   "QSpinBox::up-arrow {\n"
                                   "image:url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px.png\");\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "QSpinBox::up-button { \n"
                                   "subcontrol-origin:border;\n"
                                   "  subcontrol-position:right;   \n"
                                   "  width: 22px;\n"
                                   "  height: 20px;\n"
                                   "border:0;\n"
                                   " }\n"
                                   "\n"
                                   "\n"
                                   " \n"
                                   "QSpinBox::down-arrow { \n"
                                   "image:url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px.png\");}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   " \n"
                                   " QSpinBox::down-button { \n"
                                   "border:0px;\n"
                                   "subcontrol-origin:border;\n"
                                   "  subcontrol-position:left;\n"
                                   "  width: 22px;\n"
                                   "  height: 20px; \n"
                                   "\n"
                                   "}\n"
                                   "QSpinBox::up-button:pressed{subcontrol-origin:border;\n"
                                   "    subcontrol-position:right;\n"
                                   "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_plus_16px_2.png\");\n"
                                   "    width: 22px;\n"
                                   "    height: 20px;       \n"
                                   "}\n"
                                   "  \n"
                                   "QSpinBox::down-button:pressed\n"
                                   "{\n"
                                   "    subcontrol-position:left;\n"
                                   "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_minus_16px_2.png\");\n"
                                   "    width: 22px;\n"
                                   "    height: 20px;\n"
                                   "}\n"
                                   "")
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(424, 250, 101, 23))
        self.pushButton.setStyleSheet(".QPushButton {\n"
                                      "  background-color: white;\n"
                                      "  color: black;\n"
                                      "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                      "}\n"
                                      "\n"
                                      ".QPushButton {\n"
                                      "  transition-duration: 0.4s;\n"
                                      "}\n"
                                      "\n"
                                      ".QPushButton:hover {\n"
                                      "  background-color: rgb(85, 170, 127); /* Green */\n"
                                      "  color: white;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 530, 81, 31))
        self.pushButton_2.setStyleSheet(".QPushButton {\n"
                                        "  background-color: white;\n"
                                        "  color: black;\n"
                                        "  border: 2px solid rgb(85, 170, 127);\n"
                                        "  font: 10pt \"MS Shell Dlg 2\";\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton {\n"
                                        "  transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton:hover {\n"
                                        "  background-color: rgb(85, 170, 127); /* Green */\n"
                                        "  color: white;\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 530, 71, 31))
        self.pushButton_3.setStyleSheet(".QPushButton {\n"
                                        "  background-color: white;\n"
                                        "  color: black;\n"
                                        "  border: 2px solid rgb(85, 170, 127); /* Green */\n"
                                        "font: 10pt \"MS Shell Dlg 2\";\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton {\n"
                                        "  transition-duration: 0.4s;\n"
                                        "}\n"
                                        "\n"
                                        ".QPushButton:hover {\n"
                                        "  background-color:rgb(85, 170, 127); /* Green */\n"
                                        "  color: white;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(30, 290, 491, 221))
        self.tableWidget.setStyleSheet("\n"
                                       "QHeaderView::section\n"
                                       "\n"
                                       "{\n"
                                       " Font-size:14px; \n"
                                       " Font-family: \"Microsoft YaHei\"; \n"
                                       " Color: #FFFFFF; \n"
                                       " \n"
                                       " Background:rgb(85, 170, 127); \n"
                                       "Border:1px; \n"
                                       " Text-align:left;\n"
                                       " \n"
                                       " \n"
                                       " Min-height: 34px;\n"
                                       " max-height:34px; \n"
                                       "\n"
                                       "\n"
                                       " Margin:0px;\n"
                                       " Padding: 0px;\n"
                                       "\n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(122)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.zoneLabel_2 = QtWidgets.QLabel(self.page_4)
        self.zoneLabel_2.setGeometry(QtCore.QRect(40, 40, 81, 21))
        self.zoneLabel_2.setObjectName("zoneLabel_2")
        self.zoneComBox_2 = QtWidgets.QComboBox(self.page_4)
        self.zoneComBox_2.setGeometry(QtCore.QRect(130, 40, 71, 22))
        self.zoneComBox_2.setAcceptDrops(True)
        self.zoneComBox_2.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "")
        self.zoneComBox_2.setObjectName("zoneComBox_2")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.zoneComBox_2.addItem("")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setGeometry(QtCore.QRect(230, 40, 121, 20))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 40, 91, 20))
        self.lineEdit_7.setStyleSheet("border-bottom:1px solid #eee;\n"
                                      "border:0;\n"
                                      "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                      "border-radius:5px;\n"
                                      "height:10px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_4)
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QtCore.QRect(30, 140, 491, 221))
        self.tableWidget_2.setStyleSheet("\n"
                                         "QHeaderView::section\n"
                                         "\n"
                                         "{\n"
                                         " Font-size:14px; \n"
                                         " Font-family: \"Microsoft YaHei\"; \n"
                                         " Color: #FFFFFF; \n"
                                         " \n"
                                         " Background:rgb(85, 170, 127); \n"
                                         "Border:1px; \n"
                                         " Text-align:left;\n"
                                         " \n"
                                         " \n"
                                         " Min-height: 34px;\n"
                                         " max-height:34px; \n"
                                         "\n"
                                         "\n"
                                         " Margin:0px;\n"
                                         " Padding: 0px;\n"
                                         "\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "\n"
                                         "")
        self.tableWidget_2.setLineWidth(1)
        self.tableWidget_2.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setSelectionMode(
            QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_2.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setRowCount(0)
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(122)
        self.tableWidget_2.horizontalHeader().setHighlightSections(False)
        self.tableWidget_2.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget_2.verticalHeader().setStretchLastSection(False)
        self.bankComBox_3 = QtWidgets.QComboBox(self.page_4)
        self.bankComBox_3.setGeometry(QtCore.QRect(120, 90, 201, 22))
        self.bankComBox_3.setAcceptDrops(True)
        self.bankComBox_3.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "\n"
                                        "")
        self.bankComBox_3.setInsertPolicy(
            QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox_3.setObjectName("bankComBox_3")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.bankComBox_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.page_4)
        self.label_22.setGeometry(QtCore.QRect(40, 92, 71, 16))
        self.label_22.setObjectName("label_22")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_23 = QtWidgets.QLabel(self.page_3)
        self.label_23.setGeometry(QtCore.QRect(230, 39, 121, 20))
        self.label_23.setObjectName("label_23")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(360, 39, 91, 20))
        self.lineEdit_14.setStyleSheet("border-bottom:1px solid #eee;\n"
                                       "border:0;\n"
                                       "box-shadow:0 0 15px 4px rgba(0,0,0,0.06);\n"
                                       "border-radius:5px;\n"
                                       "height:10px;")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.bankComBox_4 = QtWidgets.QComboBox(self.page_3)
        self.bankComBox_4.setGeometry(QtCore.QRect(120, 89, 201, 22))
        self.bankComBox_4.setAcceptDrops(True)
        self.bankComBox_4.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "\n"
                                        "")
        self.bankComBox_4.setInsertPolicy(
            QtWidgets.QComboBox.InsertAfterCurrent)
        self.bankComBox_4.setObjectName("bankComBox_4")
        self.bankComBox_4.addItem("")
        self.bankComBox_4.addItem("")
        self.bankComBox_4.addItem("")
        self.bankComBox_4.addItem("")
        self.zoneLabel_5 = QtWidgets.QLabel(self.page_3)
        self.zoneLabel_5.setGeometry(QtCore.QRect(40, 39, 81, 21))
        self.zoneLabel_5.setObjectName("zoneLabel_5")
        self.zoneComBox_5 = QtWidgets.QComboBox(self.page_3)
        self.zoneComBox_5.setGeometry(QtCore.QRect(130, 39, 71, 22))
        self.zoneComBox_5.setAcceptDrops(True)
        self.zoneComBox_5.setStyleSheet("\n"
                                        ".QComboBox{\n"
                                        "    border: 2px solid #4CAF50;\n"
                                        " }\n"
                                        "\n"
                                        "\n"
                                        "\n"
                                        "QComboBox::down-arrow {\n"
                                        "    position: relative;\n"
                                        "     height: 15px;\n"
                                        "     width: 15px;\n"
                                        "    border: 12px;\n"
                                        " \n"
                                        "    image: url(\"C:/Users/haseeb/AppData/Local/Temp/icons8_expand_arrow_32px.png\")\n"
                                        "}\n"
                                        "QComboBox::drop-down {\n"
                                        "    border: 0px; \n"
                                        "}\n"
                                        "")
        self.zoneComBox_5.setObjectName("zoneComBox_5")
        self.zoneComBox_5.addItem("")
        self.zoneComBox_5.addItem("")
        self.zoneComBox_5.addItem("")
        self.zoneComBox_5.addItem("")
        self.label_24 = QtWidgets.QLabel(self.page_3)
        self.label_24.setGeometry(QtCore.QRect(40, 91, 71, 16))
        self.label_24.setObjectName("label_24")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(-1, 9, 801, 701))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.raise_()
        self.frame.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(self.showAddQuotaionTab)
        self.pushButton_6.clicked.connect(self.showAddBillTab)
        self.pushButton_8.clicked.connect(self.showQuotaionTab)
        self.pushButton_9.clicked.connect(self.showBillTab)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def showAddQuotaionTab(self):
        self.stackedWidget.setCurrentIndex(0)

    def showAddBillTab(self):
        self.stackedWidget.setCurrentIndex(1)

    def showQuotaionTab(self):
        self.stackedWidget.setCurrentIndex(2)

    def showBillTab(self):
        self.stackedWidget.setCurrentIndex(3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Add A Quotation"))
        self.pushButton_6.setText(_translate("MainWindow", "Add A Bill"))
        self.pushButton_8.setText(_translate("MainWindow", "Quotations"))
        self.pushButton_9.setText(_translate("MainWindow", "Bills"))
        self.zoneLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Zone:</span></p></body></html>"))
        self.zoneComBox.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox.setItemText(3, _translate("MainWindow", "KPK"))
        self.label_2.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Branch:</span></p></body></html>"))
        self.branchAddress.setPlaceholderText(
            _translate("MainWindow", "Enter Bank Branch Address"))
        self.label_3.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Bank:</span></p></body></html>"))
        self.bankComBox.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox.setItemText(2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox.setItemText(3, _translate(
            "MainWindow", "DUBAI ISLAMIC BANK"))
        self.label_4.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainWindow", "1"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_5.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Date of Complaint:</span></p></body></html>"))
        self.label_6.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Visit / Conveynce Charges:</span></p></body></html>"))
        self.visitTypeComBox.setItemText(0, _translate("MainWindow", "Visit"))
        self.visitTypeComBox.setItemText(
            1, _translate("MainWindow", "Conveynce"))
        self.label_7.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Services:</span></p></body></html>"))
        self.label_8.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Service Description:</span></p></body></html>"))
        self.label_9.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Details:</span></p></body></html>"))
        self.label_10.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Quantity:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Add A Service"))
        self.pushButton_2.setText(_translate("MainWindow", "Finalize"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Qty"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rate"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        self.zoneLabel_2.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Zone:</span></p></body></html>"))
        self.zoneComBox_2.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox_2.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox_2.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox_2.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox_2.setItemText(3, _translate("MainWindow", "KPK"))
        self.label_11.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Complain No"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bank Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bank Address"))
        self.bankComBox_3.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox_3.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox_3.setItemText(
            2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox_3.setItemText(
            3, _translate("MainWindow", "DUBAI ISLAMIC BANK"))
        self.label_22.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Bank:</span></p></body></html>"))
        self.label_23.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter Complaint No.</span></p></body></html>"))
        self.bankComBox_4.setItemText(
            0, _translate("MainWindow", "BANK AL-HABIB"))
        self.bankComBox_4.setItemText(
            1, _translate("MainWindow", "BANK AL-FALAH"))
        self.bankComBox_4.setItemText(
            2, _translate("MainWindow", "MEHRAN BANK"))
        self.bankComBox_4.setItemText(
            3, _translate("MainWindow", "DUBAI ISLAMIC BANK"))
        self.zoneLabel_5.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Zone:</span></p></body></html>"))
        self.zoneComBox_5.setCurrentText(_translate("MainWindow", "LHR"))
        self.zoneComBox_5.setItemText(0, _translate("MainWindow", "LHR"))
        self.zoneComBox_5.setItemText(1, _translate("MainWindow", "GUJ"))
        self.zoneComBox_5.setItemText(2, _translate("MainWindow", "FSD"))
        self.zoneComBox_5.setItemText(3, _translate("MainWindow", "KPK"))
        self.label_24.setText(_translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Select Bank:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
